on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: ./testDir/
    - name: Hey test
      run:  mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "SHOW DATABASES"
