on: [push]


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Shutdown the Default MySQL
        run: sudo service mysql stop
      - name: Set up MySQL 5.7
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 5.7
          mysql database: testThings
          mysql root password: root
      - name: Integration test with MySQL 5.7
        run:  mysql  --port 3306 -uroot -proot -e "SHOW DATABASES"
