on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3307 # Optional, default value is 3306. The port of host
        container port: 3307 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql root password: root # Required if "mysql user" is empty, default is empty. The root superuser password
    - name: Hey test

      run: |
        sleep 5
        mysql --host 127.0.0.1 --port 3307 -uroot -proot -e "SHOW DATABASES"
