on: [push]


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Start mysql
        run: |
            which mysql || echo "no mysql"
            which mysqld || echo "no mysqld"
            systemctl status mysql || echo "no status"
            echo "[mysqld]" > my.cnf
            echo "lower_case_table_names  = 1" >> my.cnf
            sudo cp my.cnf /etc/my.cnf
            sudo systemctl start mysql || echo "no start"
            sudo systemctl status mysql || echo "no status"
            
      - name: Integration test with MySQL 5.7
        run: |
          sleep 10; mysql --host 127.0.0.1  -uroot -proot -e "SHOW variables" || echo "no mysql"
          systemctl status mysql  || echo "not system"
          which mysqld || echo "meep"
          cat /etc/my.cnf || echo "no my.cnf"
      - name: V2
        run: |
          sudo apt install -y mysql-client  || echo "ree"
          sudo apt install -y mysql-server  || echo "ree2"
          systemctl status mysql || systemctl status mysqld || echo "ree4"
