on: [push]


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Integration test with MySQL 5.7
        run:  sleep 10; mysql --host 127.0.0.1  --port 3306 -uroot -proot -e "SHOW DATABASES"
