on: [push]


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Integration test with MySQL 5.7
        run: |
          sleep 10; mysql --host 127.0.0.1  -uroot -proot -e "SHOW DATABASES" || echo "no mysql"
          systemctl status mysql  || echo "not system"
          which mysqld || echo "meep"
          cat /etc/my.cnf || echo "no my.cnf"
      - name: V2
        run: |
          sudo apt install -y mysql-client  || echo "ree"
          sudo apt install -y mysql-server  || echo "ree2"
          systemctl status mysql || systemctl status mysqld || echo "ree4"
